---
title: "First Example of SimSST"
author: "Mohsen Soltanifar"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Vignette Info

```{r}
library(SimSST)
```

### Example1. Paper: Fixed SSD method

```{r}
rm(list=ls())
pid <- c("FNLN1","FNLN1")
block <- c(1,2)
n <- c(10,10) 
m <- c(4,4)   
SSD.b <- c(220,240)
dist.go <- c("ExG","ExG")
theta.go <- as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))) 
dist.stop <- c("ExG","ExG")
theta.stop <- as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70)))
mySSTdata1 <- SstSimulatedFixedSsd(pid,n,m,SSD.b,dist.go,theta.go,dist.stop,theta.stop)
#View(mySSTdata1)
mySSTdata1 
```

### Example2.Paper: Tracking Method
```{r eval=FALSE}
pid<-c("FNLN1","FNLN1")
block<-c(1,2)
n<-c(10,10) 
m<-c(4,4)   
SSD.b<-c(220,240)
dist.go=c("ExG","ExG" )
theta.go= as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))) 
dist.stop=c("ExG","ExG" )
theta.stop=as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70)))
mySSTdata2<-SstSimulatedTrackingMethod(pid,n,m,SSD.b,dist.go,theta.go,dist.stop,theta.stop)
View(mySSTdata2)
```

To convert  SimSST simulated data to BEESTS software input data, add this function in the vineggette:

### Example: Tracking Method

```{r eval=FALSE}
Datatemp2<-mySSTdata2 
ss_presented<-recode(Datatemp2[,2], 'Stop' = "1", 'Go' = "0")
inhibited<-Datatemp2[,3]
ssd<-Datatemp2[,7]
rt<-Datatemp2[,4]
srrt<-Datatemp2[,6]
Data2<-cbind.data.frame(ss_presented,inhibited,ssd,rt,srrt)
for(i in 1:10){ if(Data2$inhibited[i]==0){Data2$rt[i]<-Data2$srrt[i]}}
myBEESTSdata2<-Data2[,-5]
View(myBEESTSdata2)
```

Once we reformat the datasets to BEESTS dataset format, the user feeds the BEESTS data to the BEESTS software to get their parameters (mu, sigma, tau). 



