---
title: "First Example of SimSST"
author: "Mohsen Soltanifar"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{First Example of SimSST}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Vignette Info

```{r}
rm(list=ls())
library(SimSST)
library(dplyr)
set.seed(1)
```

### Example1. Paper: Fixed SSD method

```{r}
# pid <- c("FNLN1","FNLN1")
# block <- c(1,2)
# n <- c(10,10) 
# m <- c(4,4)   
# SSD.b <- c(220,240)
# dist.go <- c("ExG","ExG")
# theta.go <- as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))) 
# dist.stop <- c("ExG","ExG")
# theta.stop <- as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70)))
mySSTdata1 <- 
  SstSimulatedFixedSsd(
    pid=c("FNLN1","FNLN1"),
    n=c(10,10), m=c(4,4), SSD.b=c(220,240),
    dist.go=c("ExG","ExG"),
    theta.go=as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))),
    dist.stop=c("ExG","ExG"),
    theta.stop=as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70))), 
    block = c(1,2))
#View(mySSTdata1)
mySSTdata1 
```

### Example2.Paper: Tracking Method
```{r}
# pid<-c("FNLN1","FNLN1")
# block<-c(1,2)
# n<-c(10,10) 
# m<-c(4,4)   
# SSD.b<-c(220,240)
# dist.go=c("ExG","ExG" )
# theta.go= as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))) 
# dist.stop=c("ExG","ExG" )
# theta.stop=as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70)))

mySSTdata2 <- 
  SstSimulatedTrackingMethod(
    pid=c("FNLN1","FNLN1"),
    n=c(10,10), m=c(4,4), SSD.b=c(220,240), 
    dist.go=c("ExG","ExG" ),
    theta.go=as.matrix.data.frame(rbind(c(440,90,90),c(440,90,90))),
    dist.stop=c("ExG","ExG" ),
    theta.stop=as.matrix.data.frame(rbind(c(120,80,70),c(120,80,70))), 
    block=c(1,2))
# View(mySSTdata2)
mySSTdata2
```

To convert  SimSST simulated data to BEESTS software input data, add this function in the vineggette:

### Example: Tracking Method

```{r}
Datatemp2<-mySSTdata2 
ss_presented<-recode(Datatemp2[,3], 'Stop' = "1", 'Go' = "0")
inhibited<-Datatemp2[,4]
ssd<-Datatemp2[,8]
rt<-Datatemp2[,5]
srrt<-Datatemp2[,7]
Data2<-cbind.data.frame(ss_presented,inhibited,ssd,rt,srrt)
for(i in 1:20){ if(Data2$inhibited[i]==0){Data2$rt[i]<-Data2$srrt[i]}}
myBEESTSdata2<-(Data2[,-5])[order(ss_presented),]
# View(myBEESTSdata2)
myBEESTSdata2
```

Once we reformat the datasets to BEESTS dataset format, the user feeds the BEESTS data to the BEESTS software to get their parameters (mu, sigma, tau). 



